### PR TITLE
fix crash game

### PR DESCRIPTION
**Pull request by luuxis**
forge make a verification of the uuid even in crack, which causes a crash of the game in solo

### CODE REVIEW

**Comment by Pierce01** [comment]
I will not accept any PRs that have "support cracked versions" as a reason. If you want a PR to be merged, please use the correct terminology. MCLC is not a solution to play Minecraft for free. 

**Offline** support is provided so developers can test their code as well as allow players to play without internet. Take this statement as you will.

**Comment by luuxis** [comment]
so why did you add a change API function??

**Comment by Pierce01** [comment]
The same reason why I provided overrides for where content is downloaded from. If a user is in a country where Mojang's servers are blocked and require a proxy, the API URL can be changed to said proxy.

**Comment by luuxis** [comment]
ok thank you for your answer, I redo my PR to make it correct

**Pull request closed without merging**
