### PR TITLE
Split large MCLCore#launch into multiple methods

### PR DESCRIPTION
**Pull request by KevSlashNull**
This PR splits up the `MCLCore#launch` method into multiple smaller methods which should increase the readability.

It should not change any functionality.

### CODE REVIEW

**Comment by KevSlashNull** [comment]
Hey @Pierce01, could you please review this PR to refactor the `components/launcher.js` a bit? :bow:

**Comment by Pierce01** [comment]
I will definitively check this out in a bit! Thank you so much for contributing, Kev!

**Comment by Pierce01** [comment]
Though, now that I realize it, the TS types need to be added, right?

**Comment by KevSlashNull** [comment]
> Though, now that I realize it, the TS types need to be added, right?

@Pierce01, depends on if we want to expose the methods. I think it’s okay to add them as `private` or `protected` methods because they serve no use to the developer and should be hidden.

**Pull request merged**
